set up input and click for further content
the-collab-lab/tcl-5-smart-shopping-list pull request #34
Opened 2020-03-31 01:15 UTC by AshlingH

Issue: As a user, I want to see a welcoming prompt to add my first item if my list is empty to help me get oriented to how the app works 

AC: The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item

Plan: 

- Set up welcome prompt- hover click imput and hidden content detailing how the app works
-  Add CSS to make it look nice
-  Connect to add item.

2020-04-03 06:12 UTC, jonbascos reviewed
Good work you two!  I'm going to have to find out what htmlFor does.  Never seen it before.

2020-04-03 12:06 UTC, laurenmbeatty commented
I wonder if this prompt is supposed to be on the Shopping List page...it seems like from the AC that if the user is on the Shopping List page, but doesn't have any items, it should show them a prompt to add their first item.

2020-04-04 23:22 UTC, jendevelops commented
> I wonder if this prompt is supposed to be on the Shopping List page...it seems like from the AC that if the user is on the Shopping List page, but doesn't have any items, it should show them a prompt to add their first item.

Commits e5f7834 and a03ea0b address this issue. The button and message have been moved to the ShoppingList view.

2020-04-04 23:30 UTC, dkimlim reviewed
Good job, it's looking really nice :D

We might have some merge conflicts in ShoppingList this week, just a heads up!

2020-04-04 23:30 UTC, dkimlim commented on src/pages/Home.js
> +/*import '../App.css';*/
could remove commented out App.css

2020-04-04 23:57 UTC, laurenmbeatty commented on src/pages/ShoppingList.js
> +		if(token){
nice!

2020-04-04 23:59 UTC, laurenmbeatty commented on src/pages/ShoppingList.js
> +					You're list looks empty. Need help?
nice use of `htmlFor`

2020-04-04 23:59 UTC, laurenmbeatty commented on src/pages/ShoppingList.js
> +					You're list looks empty. Need help?
```suggestion
					Your list looks empty. Need help?
```

2020-04-05 12:04 UTC, laurenmbeatty requested changes
Just that one spelling fix, then you're good to go.

2020-04-07 01:50 UTC, merged

2020-04-07 01:51 UTC, jendevelops commented
Closes #8