I want to view details of my purchases to better understand my purchase patterns #14
the-collab-lab/tcl-5-smart-shopping-list pull request #43
Opened 2020-04-23 05:44 UTC by AshlingH

## Description

This code creates an exciting feature. The user is able to click on a purchased item, a modal will show , item details are shown on screen.

## Related Issue
#13 

## Acceptance Criteria

- From the shopping list, user can tap to navigate to a detailed view of the item

- Detail view includes the following information:
     - Name of the item
     - Last purchased date
     - Estimated number of days until the next purchase
     - Number of times the item has been purchased"

- When in the “item details” view, a back arrow should appear in the header that takes the user back to the “list” view

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates
Creating New modal to show item details so user is better able to make decisions of when to next purcahse the item.

2020-04-24 03:14 UTC, jonbascos reviewed
Looks awesome!  I really like the unpacking of the props too.  That's something I should start doing.  It makes more sense than just putting in the word 'props'.  Looks clean!

2020-04-24 11:52 UTC, laurenmbeatty commented on src/lib/timeframeConstants.js
> +export {SOON, KIND_OF_SOON, NOT_SOON, INACTIVE, returnString};
Love this file! Well done....so handy!

2020-04-24 11:54 UTC, laurenmbeatty commented on src/pages/ShoppingList.js
>                  {filterString
This `tbody` should be wrapped in a `<table>` tag, too. Then you will get the table styles back:
![image](https://user-images.githubusercontent.com/10378331/80209793-53a61b80-85f8-11ea-9baa-1e529bf8d2ca.png)

![image](https://user-images.githubusercontent.com/10378331/80209871-6b7d9f80-85f8-11ea-9c62-70b59943e579.png)

2020-04-25 01:28 UTC, dkimlim commented on src/components/ShoppingListItem.js
> +            <td>{returnString("value",item.timeFrame)}</td>
yeyy! So nice you were able to refactor this

2020-04-25 01:30 UTC, dkimlim commented on src/lib/timeframeConstants.js
> +    if(type === "class"){
cool little function :)

2020-04-25 01:31 UTC, dkimlim approved these changes
SOOOO good reading your PR this week! Good job ya'll, it's looking squeaky clean

2020-04-25 02:35 UTC, laurenmbeatty commented on src/components/Modal.js
> +                <h2>{item.name}</h2>
```suggestion
                <h2>{item.itemName}</h2>
```
The name isn't showing up in the modal...I think it needs to be `item.itemName`

2020-04-25 02:38 UTC, laurenmbeatty requested changes
This looks fantastic. Just one tiny bug with the item name in the modal. One thing that would be a "nice-to-have"...could you make it so if I have the details modal open, and then click the delete button, that the details modal closes? Same thing if I have the delete modal open, and then click the details modal...could the delete modal close?

2020-04-25 23:29 UTC, laurenmbeatty approved these changes
Nice!  Thanks for the change @AshlingH !  This looks great.

2020-04-28 01:32 UTC, merged